### ISSUE TITLE
Does the tools unescape &#039;

### ISSUE THREAD

**Issue by jjayaraman** [wesleytodd/recursive-unescape#2]
Thanks for the nice tool.
Does it also escape  `&#039;`

I tried the below text and it's not working
Example text: `'The &#039;Squaring the Circle&#039; problem is solvable.'`

**Comment by wesleytodd** [comment]
Hi @jjayaraman, it is just a [wrapper around `lodash.unescape`](https://github.com/wesleytodd/recursive-unescape/blob/master/index.js#L1), so I would look to those docs.  Hope that helps!
